// <auto-generated />
namespace EnglishForCoachesWeb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class articuloV2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(articuloV2));
        
        string IMigrationMetadata.Id
        {
            get { return "201605020639434_articuloV2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
