// <auto-generated />
namespace EnglishForCoachesWeb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AhorcadoV2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AhorcadoV2));
        
        string IMigrationMetadata.Id
        {
            get { return "201907301035241_AhorcadoV2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
